# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'QSCardBanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QSCardBanner
pod 'Kingfisher'
pod 'QSExtensions'
pod 'SnapKit'
end
